# Generated by Django 2.0.1 on 2018-01-12 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('turn', models.IntegerField()),
                ('rate', models.FloatField()),
                ('date', models.DateTimeField()),
                ('loan_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
